version: '3'
services:
  cockroachdb:
    build:
      dockerfile: cockroach/Dockerfile
      context: .
    ports:
      - "$COCKROACHDB_PORT:$COCKROACHDB_PORT"
      - "$COCKROACH_DB_EXPOSE_HTTP_PORT:$COCKROACH_DB_EXPOSE_HTTP_PORT"
    command: "./cockroach/run.sh"
    environment:
      - COCKROACH_USER=hwboard
      - COCKROACH_DB=hwboard
    volumes:
      - ./cockroach:/cockroach
  web:
    restart: always
    build: .
    ports:
      - "$HWBOARD_PORT:$HWBOARD_PORT"
    command: "/bin/bash -c 'npm start;while :; do sleep 2073600; done'"
    environment:
      - IS_DOCKER=true
      - POSTGRES_DB=hwboard
      - POSTGRES_PASSWORD=incorrect_spaghett
      - POSTGRES_USER=hwboard
    depends_on:
      - "cockroachdb"
    volumes:
      - ./:/hwboard2
