version: '3'
services:
  cockroachdb:
    build:
      dockerfile: Dockerfile-cockroach
      context: .
    ports:
      - "26257:26257"
      - "8080:8080"
    command: "/bin/bash -c 'while :; do sleep 2073600; done'"
    environment:
      - COCKROACH_USER=hwboard
      - COCKROACH_DB=hwboard
  web:
    restart: always
    build: .
    ports:
      - "3001:3001"
    command: "./wait-for-it.sh cockroachdb:26257 -- /bin/bash -c 'while :; do sleep 2073600; done'"
    environment:
      - IS_DOCKER=true
      - POSTGRES_DB=hwboard
      - POSTGRES_PASSWORD=incorrect_spaghett
      - POSTGRES_USER=hwboard
    depends_on:
      - "cockroachdb"
    volumes:
      - ./:/hwboard2
