version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
    - /var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=hwboard
      - POSTGRES_DB=hwboard
      - POSTGRES_PASSWORD=incorrect_spaghett
  web:
    restart: always
    build: .
    ports:
      - "$HWBOARD_PORT:$HWBOARD_PORT"
    command: "/bin/bash -c 'npm start;while :; do sleep 2073600; done'"
    environment:
      - IS_DOCKER=true
      - POSTGRES_DB=hwboard
      - POSTGRES_PASSWORD=incorrect_spaghett
      - POSTGRES_USER=hwboard
    depends_on:
      - "postgres"
    volumes:
      - ./:/home/hwboard/hwboard2
