version: '3'
services:
  postgres:
    restart: always
    image: postgres:10-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=hwboard
      - POSTGRES_PASS=incorrect_spaghett
      - POSTGRES_NAME=hwboard
  web:
    restart: always
    build: .
    ports:
      - "3001:3001"
    expose:
      - "3001"
    command: "./wait-for-it.sh postgres:5432 -- /bin/bash -c 'while :; do sleep 2073600; done'"
    environment:
      - IS_DOCKER=true
      - HWBOARD_PORT=3001
      - POSTGRES_DB=hwboard
      - POSTGRES_PASSWORD=incorrect_spaghett
      - POSTGRES_USER=hwboard
    depends_on:
      - "postgres"
